ASSET_TYPES = {
    "techblogs": {
        "display_default": 1,
        "display_sort_order": 1,
        "display_title": "TechBlog Posts",
        "group": "Written Content",
        "group_sort_order": 2,
        "name": "techblogs",
    },
    "summarize_techblogs": {
        "display_default": 1,
        "display_sort_order": 2,
        "display_title": "TechBlog Posts Summaries",
        "group": "Written Content",
        "group_sort_order": 2,
        "name": "summarize_techblogs",
    },
    # "nvblogs": {
    #     "display_default": 1,
    #     "display_sort_order": 2,
    #     "display_title": "NVIDIA Blog Posts",
    #     "group": "Written Content",
    #     "group_sort_order": 2,
    #     "name": "nvblogs",
    # },
    # "sdks": {
    #     "display_default": 1,
    #     "display_sort_order": 1,
    #     "display_title": "SDKs",
    #     "group": "Software",
    #     "group_sort_order": 3,
    #     "name": "sdks",
    # },
    # "ngccontainers": {
    #     "display_default": 1,
    #     "display_sort_order": 2,
    #     "display_title": "NGC Containers",
    #     "group": "Software",
    #     "group_sort_order": 3,
    #     "name": "ngccontainers",
    # },
    # "ngcmodels": {
    #     "display_default": 1,
    #     "display_sort_order": 3,
    #     "display_title": "NGC Models",
    #     "group": "Software",
    #     "group_sort_order": 3,
    #     "name": "ngcmodels",
    # },
    # "ngcresources": {
    #     "display_default": 1,
    #     "display_sort_order": 4,
    #     "display_title": "NGC Resources",
    #     "group": "Software",
    #     "group_sort_order": 3,
    #     "name": "ngcresources",
    # },
    # "developernvidiacom": {
    #     "display_default": 1,
    #     "display_sort_order": 2,
    #     "display_title": "developer.nvidia.com",
    #     "group": "NVIDIA Web Pages",
    #     "group_sort_order": 4,
    #     "name": "developernvidiacom",
    # },
}
